package canonical

import (
	"encoding/json"
	"testing"
)

// These two vectors are the worked examples captured from Presto in
// go-plan.md §3.4. They are transcribed by hand from that document, not
// generated by this package, which is the whole point of a vector: an
// implementation bug here cannot leak into its own proof.

func TestBuild_SigningExample(t *testing.T) {
	fields := map[string]any{
		"mid":          "PW2401XH9KCX",
		"prestoMrn":    "PM240110XDSFC",
		"txnType":      "WebPay",
		"txnRefNum":    "TXN10001",
		"displayDesc":  "Order #12345",
		"amount":       json.Number("1200"),
		"currencyCode": "MYR",
		"notifyUrl":    "https://merchant.example.com/webhook/notify",
		"redirectUrl":  "https://merchant.example.com/redirect/TXN10001",
		"ts":           "20250423104500.000",
	}
	want := "1200:MYR:Order #12345:PW2401XH9KCX:https://merchant.example.com/webhook/notify:PM240110XDSFC:https://merchant.example.com/redirect/TXN10001:20250423104500.000:TXN10001:WebPay"

	got, err := Build(fields)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if got != want {
		t.Fatalf("Build() = %q, want %q", got, want)
	}
}

func TestBuild_BusinessErrorExample(t *testing.T) {
	fields := map[string]any{
		"success":      false,
		"ts":           "20260924124938.038",
		"errorCode":    "1201",
		"errorMessage": "Invalid input.",
		"signature":    "should be excluded",
	}
	want := "1201:Invalid input.:false:20260924124938.038"

	got, err := Build(fields)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if got != want {
		t.Fatalf("Build() = %q, want %q", got, want)
	}
}

// The successful init response in go-plan.md §3.4 is the vector that settles
// how null is rendered: additionalData sorts first and must contribute an
// empty string plus its separator, not be dropped and not render as "null".
func TestBuild_NullRendersAsEmptyString(t *testing.T) {
	fields := map[string]any{
		"additionalData":       nil,
		"amount":               json.Number("200"),
		"currencyCode":         "MYR",
		"errorCode":            "",
		"errorMessage":         "",
		"paymentFinalisedDate": "",
		"paymentRefNum":        "PP260924K4H3DSF",
		"paymentRequestDate":   "20260924133756.056",
		"paymentStatus":        "PendingAuthorise",
		"paymentUrl":           "https://hpp-staging.prestouniverse.com/PM181019QGJWH4K/PP260924K4H3DSF",
		"prestoMrn":            "PM181019QGJWH4K",
		"success":              true,
		"ts":                   "20260924133756.056",
		"txnRefNum":            "PM202609244E33DA4FCCC7445B99821588791F2418",
		"userRefNum":           "",
	}
	want := ":200:MYR::::PP260924K4H3DSF:20260924133756.056:PendingAuthorise:" +
		"https://hpp-staging.prestouniverse.com/PM181019QGJWH4K/PP260924K4H3DSF:" +
		"PM181019QGJWH4K:true:20260924133756.056:PM202609244E33DA4FCCC7445B99821588791F2418:"

	got, err := Build(fields)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if got != want {
		t.Fatalf("Build() = %q, want %q", got, want)
	}
}

func TestBuild_RejectsNonIntegerNumber(t *testing.T) {
	_, err := Build(map[string]any{"amount": json.Number("12.5")})
	if err == nil {
		t.Fatal("expected an error for a non-integer number")
	}
}

func TestBuild_RejectsArraysAndObjects(t *testing.T) {
	for _, v := range []any{[]any{1, 2}, map[string]any{"a": 1}, 1.5} {
		if _, err := Build(map[string]any{"x": v}); err == nil {
			t.Fatalf("expected an error for value %#v", v)
		}
	}
}

func TestBuild_EmptyKeyKeepsSeparator(t *testing.T) {
	got, err := Build(map[string]any{"a": "x", "b": nil, "c": "y"})
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if want := "x::y"; got != want {
		t.Fatalf("Build() = %q, want %q", got, want)
	}
}
